"""1

Revision ID: 42b150e26f1d
Revises: 
Create Date: 2023-03-20 12:39:13.995617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b150e26f1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_map', sa.Column('original', sa.String(length=256), nullable=False))
    op.drop_column('url_map', 'origimal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_map', sa.Column('origimal', sa.VARCHAR(length=256), nullable=False))
    op.drop_column('url_map', 'original')
    # ### end Alembic commands ###
